apiVersion: v1
kind: Pod
metadata:
  name: github-runner
  namespace: sc 
  labels:
    app: github-runner
spec:
  initContainers:
  - name: config-runner
    image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/github-runner:v1.1
    command: ["/actions-runner/config.sh"]
    env:
    - name: RUNNER_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-runner-token
          key: TOKEN
    args: ["--unattended", "--url", "https://github.com/input-output-hk/sidechains-tests", "--token", "$(RUNNER_TOKEN)"]
    volumeMounts:
    - name: runner-config
      mountPath: /actions-runner

  containers:
  - name: github-runner
    image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/github-runner:v1.1
    imagePullPolicy: IfNotPresent
    env:
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    volumeMounts:
    - name: ipc
      mountPath: /ipc
    - name: runner-config
      mountPath: /actions-runner
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  - name: cardano-node
    image: inputoutput/cardano-node:1.35.4
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "2048Mi"
        cpu: "1000m"
      requests:
        memory: "2048Mi"
        cpu: "1000m"
    env:
    - name: NETWORK
      value: "preview"
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    volumeMounts:
    - name: ipc
      mountPath: /ipc
    - name: cardano-node-data
      mountPath: /data
  volumes:
  - name: ipc
    emptyDir: {}
  - name: runner-config
    emptyDir: {}
  - name: cardano-node-data
    persistentVolumeClaim:
      claimName: github-runner-claim-cardano-node-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-runner-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
