---
apiVersion: v1
kind: Service
metadata:
  name: greg-service
  namespace: sc
spec:
  type: NodePort
  selector:
    app: sidechains-substrate-poc
    node: greg
  ports:
    - name: p2p-port
      port: 30333
      targetPort: 30333
      nodePort: 30007
    - name: rpc-port
      port: 9933
      targetPort: 9933
      nodePort: 30027
    - name: vector-metrics
      port: 9182
      targetPort: 9182
    - name: substrate-node-metrics
      port: 9615
      targetPort: 9615
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: greg-vector-configmap
  namespace: sc
data:
  vector.toml: |
    # Vector's API for introspection
    [api]
    enabled = true
    address = "127.0.0.1:8686"
    playground = true

    # Input data from Kubernetes
    [sources.kubernetes_logs]
    type = "kubernetes_logs"

    # Collect Vector's internal metrics
    [sources.internal_metrics]
    type = "internal_metrics"

    # Collect Host metrics
    [sources.host_metrics]
    type = "host_metrics"
    collectors = ["cpu", "disk", "memory", "network"]

    # Transform data
    [transforms.remap]
    type = "remap"
    inputs = ["kubernetes_logs"]
    source = '''
    .processed_at = now()
    '''

    # Send data to Loki
    [sinks.loki]
    type = "loki"
    inputs = ["remap"]
    endpoint = "http://monitoring-service.sc:3100"
    encoding.codec = "json"
    labels.environment = "production"
    labels.application = "greg-service"

    # Prometheus Metrics
    [sinks.prometheus]
    type = "prometheus_exporter"
    inputs = ["remap", "internal_metrics", "host_metrics"]
    address = "0.0.0.0:9182"
---
apiVersion: v1
kind: Pod
metadata:
  name: greg
  namespace: sc
  labels:
    app: sidechains-substrate-poc
    node: greg
    substrate-node: 'true'
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9615'
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: substrate-node
            operator: In
            values:
            - 'true'
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    pod: greg
  containers:
    - name: cardano-node
      image: inputoutput/cardano-node:8.0.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "1000m"
        requests:
          memory: "4096Mi"
          cpu: "1000m"
      env:
        - name: NETWORK
          value: "preview"
        - name: CARDANO_NODE_SOCKET_PATH
          value: /ipc/node.socket
      volumeMounts:
        - name: ipc
          mountPath: /ipc
        - name: cardano-node-data
          mountPath: /data
    - name: db-sync
      image: inputoutput/cardano-db-sync:13.1.1.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "500m"
        requests:
          memory: "4096Mi"
          cpu: "500m"
      env:
        - name: NETWORK
          value: "preview"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - name: ipc
          mountPath: /node-ipc
        - name: db-sync-state-dir
          mountPath: /var/lib
    - name: postgres
      image: postgres:15.3
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "2048Mi"
          cpu: "500m"
        requests:
          memory: "2048Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
    - name: bridge-backend
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/bridge-backend:0.16.0
      command: [ "/opt/docker/bin/bridge-backend", "-Dmainchain.epoch-duration=86400000", "-Dmainchain.security-parameter=432" ]
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "512Mi"
          cpu: "500m"
      env:
        - name: BRIDGE_BACKEND_SOCKET_PATH
          value: "/ipc/bridge.socket"
        - name: CARDANO_FOLLOWER_POSTGRES_USERNAME
          value: "postgres"
        - name: CARDANO_FOLLOWER_POSTGRES_PASSWORD
          value: "password123"
        - name: CARDANO_FOLLOWER_JDBC_URL
          value: "jdbc:postgresql://localhost:5432/cexplorer"
        - name: FUEL_MINTING_POLICY_ID
          value: "68a3a1612b486b791e02de34f39114d5cd44afceeb071c8a566cd1d6"
        - name: COMMITTEE_CANDIDATE_ADDRESS
          value: "addr_test1wr9m7pch0at7lt34783drfn6uxlnhxd2lsnz6am085c7e4cthzmd8"
        - name: COMMITTEE_NFT_POLICY_ID
          value: "e67a32f6f21dcaa93b15716fb528c196b64397c3bbf61700c4a0fd98"
        - name: MERKLE_ROOT_NFT_POLICY_ID
          value: "08a2afd7a0156501acfa324febf618061d55260dd94da757aaa567b3"
        - name: DISTRIBUTED_SET_POLICY_ID
          value: "87ffa8fb6e62c929d9c134307b9a374a601914a93760f7ae9526a8ad"
        - name: BRIDGE_BACKEND_GRPC_TYPE
          value: "http2"
        - name: BRIDGE_BACKEND_GRPC_PORT
          value: "18080"
        - name: COMMITTEE_NFT_ADDRESS
          value: "addr_test1wp5rwrw55e2e63gs0a2zjyrjln05w8v0d3sn5vh2ms84jjckgcwem"
        - name: MERKLE_ROOT_NFT_ADDRESS
          value: "addr_test1wp3hsru6sasaz0cpm02shn4uhzeq26y73v6lcz36uf3e20s643uq5"
        - name: DISTRIBUTED_SET_NFT_ADDRESS
          value: "addr_test1wpjj5ac463htxu3slmlq2jtpyy52ewr9ueh24g0nksn0v5c3uzx48"
        - name: D_PARAMETER_POLICY_ID
          value: "e87721ed30264111c947f9976279dbcdc3ff4f9c70633555ecd96a11"
        - name: PERMISSIONED_CANDIDATES_POLICY_ID
          value: "5a1302bbcf9ddb03d0f4d9cbf61f28caf5c69630db2c20e0bbde286f"
        - name: FUEL_ASSET_NAME
          value: "4655454c"
      volumeMounts:
        - name: ipc
          mountPath: /ipc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
    - name: substrate-node
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/substrate-node:336e859cbcd0b203215106de4563c69dd9aa8266
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "1000m"
        requests:
          memory: "4096Mi"
          cpu: "1000m"
      env:
        - name: MC__FIRST_EPOCH_TIMESTAMP_MILLIS
          value: "1666656000000"
        - name: MC__FIRST_EPOCH_NUMBER
          value: "0"
        - name: MC__EPOCH_DURATION_MILLIS
          value: "86400000"
        - name: CHAIN_ID
          value: "0"
        - name: THRESHOLD_NUMERATOR
          value: "2"
        - name: THRESHOLD_DENOMINATOR
          value: "3"
        - name: GENESIS_COMMITTEE_UTXO
          value: "88f757228c8d90c460d671682f3be5e09f8c1ef66adfded49b04a8a0dc3a7f9a#0"
        - name: GOVERNANCE_AUTHORITY
          value: "76da17b2e3371ab7ca88ce0500441149f03cc5091009f99c99c080d9"
        - name: BRIDGE_BACKEND_GRPC_TYPE
          value: "http2"
        - name: BRIDGE_BACKEND_HTTP_PORT
          value: "18080"
      args:
        - "--greg"
        - "--base-path"
        - "/data"
        - "--chain"
        - "local"
        - "--validator"
        - "--node-key"
        - "0000000000000000000000000000000000000000000000000000000000000007"
        - "--bootnodes"
        - "/dns/alice-service.sc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
        - "--unsafe-rpc-external"
        - "--rpc-port"
        - "9933"
        - "--rpc-cors=all"
        - "--prometheus-port"
        - "9615"
        - "--prometheus-external"
      ports:
        - containerPort: 30333
          name: p2p
        - containerPort: 9945
          name: ws-port
        - containerPort: 9933
          name: rpc-port
        - containerPort: 9615
          name: prometheus 
      volumeMounts:
        - name: substrate-node-data
          mountPath: /data
        - name: ipc
          mountPath: /ipc
    - name: vector
      image: timberio/vector:nightly-alpine
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "300Mi"
          cpu: "500m"
        requests:
          memory: "300Mi"
          cpu: "500m"
      env:
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName 
      ports:
        - containerPort: 8686
        - containerPort: 9182
      volumeMounts:
        - name: vector-config
          mountPath: /etc/vector
        - name: vector-logs
          mountPath: /var/log

  volumes:
    - name: cardano-node-data
      persistentVolumeClaim:
        claimName: greg-claim-cardano-node-data
    - name: postgres-data
      persistentVolumeClaim:
        claimName: greg-claim-postgres-data
    - name: substrate-node-data
      persistentVolumeClaim:
        claimName: greg-claim-substrate-node-data
    - name: db-sync-state-dir
      persistentVolumeClaim:
        claimName: greg-claim-db-sync-state-dir
    - name: ipc
      emptyDir: {}
    - name: vector-config
      configMap:
        name: greg-vector-configmap
    - name: vector-logs
      persistentVolumeClaim:
        claimName: greg-claim-vector-logs
