### Shortcuts:
### 1. use default "postgres" username, even if I've made a matching changes, I could not make login from db-sync.
### 2. db-sync deep inside sets CARDANO_NODE_SOCKET_PATH (overriding what was given from k8s env), so I made directory matching its expectations.
### Postgres is the only service with external access in this setup.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets
  namespace: sidechains-substrate-poc
data:
  postgres_db: "cexplorer"
  postgres_user: "postgres"
  postgres_password: "password123"
---
apiVersion: v1
kind: Pod
metadata:
  name: sidechain-participant
  namespace: sidechains-substrate-poc
  labels:
    app: sidechains-substrate-poc
    node: sidechain-participant
spec:
  containers:
    - name: cardano-node
      image: inputoutput/cardano-node:8.0.0
      imagePullPolicy: IfNotPresent
      env:
        - name: NETWORK
          value: "preview"
        - name: CARDANO_NODE_SOCKET_PATH
          value: /ipc/node.socket
      volumeMounts:
        - name: ipc
          mountPath: /ipc
        - name: datavol
          mountPath: /opt/cardano/data
    - name: postgres
      image: postgres:15.3
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        - name: POSTGRES_DB
          value: "cexplorer"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-run
          mountPath: /run/postgresql
    - name: db-sync
      image: inputoutput/cardano-db-sync:13.1.1.0
      env:
        - name: NETWORK
          value: "preview"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - name: ipc
          mountPath: /node-ipc
        - name: postgres-run
          mountPath: /run/postgresql
        - name: secrets
          mountPath: /run/secrets
  volumes:
    - name: ipc
      emptyDir: {}
    - name: datavol
      emptyDir: {}
    - name: postgres-data
      emptyDir: {}
    - name: postgres-run
      emptyDir: {}
    - name: secrets
      configMap:
        name: secrets
########## postgres service ##########################################################
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: sidechains-substrate-poc
spec:
  type: NodePort
  selector:
    app: sidechains-substrate-poc
    node: sidechain-participant
  ports:
    - name: tcp-5432
      port: 5432
      targetPort: 5432
