---
apiVersion: v1
kind: Pod
metadata:
  name: binary-host
  namespace: sc 
  labels:
    app: binary-host
spec:
  containers:
  - name: binary-host
    image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/binary-host:1.5
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "service ssh start && tail -f /dev/null"]
    env:
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    ports:
    - containerPort: 22
      name: ssh
    volumeMounts:
    - name: ipc
      mountPath: /ipc
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  - name: cardano-node
    image: inputoutput/cardano-node:1.35.4
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "2048Mi"
        cpu: "1000m"
      requests:
        memory: "2048Mi"
        cpu: "1000m"
    env:
    - name: NETWORK
      value: "preview"
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    volumeMounts:
    - name: ipc
      mountPath: /ipc
    - name: cardano-node-data
      mountPath: /data
  volumes:
  - name: ipc
    emptyDir: {}
  - name: cardano-node-data
    persistentVolumeClaim:
      claimName: binary-host-claim-cardano-node-data
---
apiVersion: v1
kind: Service
metadata:
  name: binary-host-service
  namespace: sc
spec:
  selector:
    app: binary-host
  ports:
  - protocol: TCP
    port: 22
    targetPort: ssh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: binary-host-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi