apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-host
  labels:
    app: binary-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-host
  template:
    metadata:
      labels:
        app: binary-host
    spec:
      containers:
      - name: binary-host-container
        image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/binary-host:v1.2
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "tail -f /dev/null"] 
