---
apiVersion: v1
kind: Secret
metadata:
  name: substrate-keys
  namespace: sc
type: Opaque
data:
  eve.payment.skey.json.decrypted: ewoJInR5cGUiOiAiUGF5bWVudFNpZ25pbmdLZXlTaGVsbGV5X2VkMjU1MTkiLAoJImRlc2NyaXB0aW9uIjogIlBheW1lbnQgU2lnbmluZyBLZXkiLAoJImNib3JIZXgiOiAiNTgyMGEwM2ZmMTFmNGYxMTMzM2UwN2Y1YTAxNWU5OWY5OGE2YTkzZDY2ZjI0ZjMxMjA3MjY2OGE2YmViNDRiODJmNzkiCn0=
  ferdie.payment.skey.json.decrypted: ewoJInR5cGUiOiAiUGF5bWVudFNpZ25pbmdLZXlTaGVsbGV5X2VkMjU1MTkiLAoJImRlc2NyaXB0aW9uIjogIlBheW1lbnQgU2lnbmluZyBLZXkiLAoJImNib3JIZXgiOiAiNTgyMDk3MmJlZTlkMDlmM2YyZmFiODdlYWRkYWNhZWNhZjZkNmU1OTgzOWI1ZTA2YWY0YWU2ZDFhNzYzMDEwNjFkYmYiCn0=
---
apiVersion: v1
kind: Pod
metadata:
  name: binary-host
  namespace: sc 
  labels:
    app: binary-host
spec:
  containers:
  - name: binary-host
    image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/binary-host:1.5
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "service ssh start && tail -f /dev/null"]
    env:
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    ports:
    - containerPort: 22
      name: ssh
    volumeMounts:
    - name: ipc
      mountPath: /ipc
    - name: substrate-keys
      mountPath: /secrets/substrate/remote/keys/eve/payment.skey.json.decrypted
      subPath: eve.payment.skey.json.decrypted
    - name: substrate-keys
      mountPath: /secrets/substrate/remote/keys/ferdie/payment.skey.json.decrypted
      subPath: ferdie.payment.skey.json.decrypted
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  - name: cardano-node
    image: inputoutput/cardano-node:1.35.4
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "2048Mi"
        cpu: "1000m"
      requests:
        memory: "2048Mi"
        cpu: "1000m"
    env:
    - name: NETWORK
      value: "preview"
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    volumeMounts:
    - name: ipc
      mountPath: /ipc
    - name: cardano-node-data
      mountPath: /data
  volumes:
  - name: ipc
    emptyDir: {}
  - name: cardano-node-data
    persistentVolumeClaim:
      claimName: binary-host-claim-cardano-node-data
  - name: substrate-keys
    secret:
      secretName: substrate-keys
---
apiVersion: v1
kind: Service
metadata:
  name: binary-host-service
  namespace: sc
spec:
  selector:
    app: binary-host
  ports:
  - protocol: TCP
    port: 22
    targetPort: ssh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: binary-host-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi