apiVersion: v1
kind: Pod
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  containers:
  - name: binary-host
    image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/binary-host:v1.4
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "cp -r /tools/* /shared-binaries/ && tail -f /dev/null"]
    volumeMounts:
    - name: shared-binaries
      mountPath: /shared-binaries
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"

  - name: cardano-node
    image: inputoutput/cardano-node:1.35.4
    imagePullPolicy: IfNotPresent
    env:
    - name: NETWORK
      value: "preview"
    - name: CARDANO_NODE_SOCKET_PATH
      value: /ipc/node.socket
    volumeMounts:
    - name: ipc
      mountPath: /ipc
    - name: cardano-node-data
      mountPath: /data
    resources:
      limits:
        memory: "2048Mi"
        cpu: "1000m"
      requests:
        memory: "2048Mi"
        cpu: "1000m"

  - args:
    - --metrics-addr=127.0.0.1:8080
    - --enable-leader-election
    - --sync-period=10m
    command:
    - /manager
    env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: github_token
          name: controller-manager
          optional: true
    - name: GITHUB_APP_ID
      valueFrom:
        secretKeyRef:
          key: github_app_id
          name: controller-manager
          optional: true
    - name: GITHUB_APP_INSTALLATION_ID
      valueFrom:
        secretKeyRef:
          key: github_app_installation_id
          name: controller-manager
          optional: true
    - name: GITHUB_APP_PRIVATE_KEY
      value: /etc/actions-runner-controller/github_app_private_key
    image: summerwind/actions-runner-controller:v0.22.0
    name: manager
    ports:
    - containerPort: 9443
      name: webhook-server
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    volumeMounts:
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: cert
      readOnly: true
    - mountPath: /etc/actions-runner-controller
      name: controller-manager
      readOnly: true
  - args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=10
    image: quay.io/brancz/kube-rbac-proxy:v0.10.0
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      name: https
  terminationGracePeriodSeconds: 10
  volumes:
  - name: cert
    secret:
      defaultMode: 420
      secretName: webhook-server-cert
  - name: controller-manager
    secret:
      secretName: controller-manager
  - name: ipc
    emptyDir: {}
  - name: cardano-node-data
    persistentVolumeClaim:
      claimName: binary-host-claim-cardano-node-data
  - name: shared-binaries
    emptyDir: {}

