# eve
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eve-vector-config
  namespace: sidechains-substrate-poc-3
data:
  vector.toml: |
    [api]
    enabled = true
    address = "0.0.0.0:8686"
    [sources.log_file]
    type = "file"
    include = ["/var/log/*.log"]
    # [sinks.prometheus]
    # type = "prometheus_exporter"
    # inputs = [ "my-source-or-transform-id" ]
    [sinks.console]
    inputs = ["log_file"]
    target = "stdout"
    type = "console"
    encoding.codec = "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eve-secrets
  namespace: sidechains-substrate-poc-3
data:
  postgres_db: "cexplorer"
  postgres_user: "postgres"
  postgres_password: "password123"
---
apiVersion: v1
kind: Pod
metadata:
  name: eve
  namespace: sidechains-substrate-poc-3
  labels:
    app: eve
    node: eve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eve
  template:
    metadata:
      labels:
        app: eve
    spec:
      containers:
        - name: eve-cardano-node
          image: inputoutput/cardano-node:8.0.0 
          env:
            - name: NETWORK
              value: "preview"
            - name: CARDANO_NODE_SOCKET_PATH
              value: /ipc/node.socket
          volumeMounts:
            - name: ipc
              mountPath: /ipc
            - name: data
              mountPath: /opt/cardano/data
        - name: eve-db-sync
          image: inputoutput/cardano-db-sync:latest 
          env:
            - name: NETWORK
              value: "preview"
            - name: POSTGRES_HOST
              value: "localhost"
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: eve-ipc
              mountPath: /node-ipc
            - name: eve-postgres-run
              mountPath: /run/postgresql
            - name: eve-secrets
              mountPath: /run/secrets
        - name: eve-postgres
          image: postgres:15.3
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: "password123"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: POSTGRES_DB
              value: "cexplorer"
          volumeMounts:
            - name: eve-data
              mountPath: /var/lib/postgresql/data
            - name: eve-postgres-run
              mountPath: /run/postgresql
        - name: eve-bridge-backend
          image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/bridge-backend
          volumeMounts:
          - name: eve-ipc
            mountPath: /node-ipc
          - name: eve-data
            mountPath: /var/lib/postgresql/data
        - name: eve-substrate-node
          image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/sidechains-substrate-node
          args: 
             - "--name"
             - "eve"
             - "--base-path"
             - "/data/eve"
             - "--chain"
             - "local"
             - "--validator"
             - "--node-key"
             - "0000000000000000000000000000000000000000000000000000000000000001"
          ports:
             - containerPort: 30333
               name: p2p
             - containerPort: 9945
               name: ws-port
             - containerPort: 9933
               name: rcp-port
          volumeMounts:
             - name: eve-data
               mountPath: /data
        - name: eve-vector
          image: timberio/vector:nightly-alpine
          ports:
            - containerPort: 8686 
          volumeMounts:
            - name: eve-vector-config
              mountPath: /etc/vector
            - name: eve-vector-logs
              mountPath: /var/log
      volumes:
        - name: eve-data
          emptyDir: {}
        - name: eve-ipc
          emptyDir: {}
        - name: eve-postgres-run
          emptyDir: {}
        - name: eve-secrets
          configMap:
            name: eve-secrets
        - name: eve-vector-config
          configMap:
            name: eve-vector-config
        - name: eve-vector-logs
          emptyDir: {}
