apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

vars:
  - name: POD_NAME
    objref:
      kind: ConfigMap
      name: alice-vector-config
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name

varReference:
  - path: metadata/name
  - path: metadata/labels
  - path: spec/template/metadata/labels
  - path: spec/containers/env/value
  - path: spec/containers/args
  - path: spec/volumes/configMap/name
