apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
- source:
    value: "alice"
  targets:
  - select: 
      kind: Service
    fieldPaths: 
    - metadata.name
    - spec.selector.node
  - select: 
      kind: ConfigMap
    fieldPaths: 
    - metadata.name
  - select: 
      kind: Pod
    fieldPaths: 
    - metadata.name
    - metadata.labels.node