apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/base.yaml

resources:
- base.yaml

replacements:
- name: namePrefix
  from: $(namePrefix)
  to: alice
- name: node-key
  from: $(node-key)
  to: 0000000000000000000000000000000000000000000000000000000000000001
- name: bootnodes
  from: $(bootnodes)
  to: /dns/alice-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp