apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/base.yaml
vars:
- name: node-key
  objref:
    kind: Service
    name: my-service
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name

replacements:
- source:
    kind: string
    name: alice
  targets:
  - select:
      name: hello
      kind: Job
    fieldPaths: 
    - spec.template.spec.containers[3].args[0]

- source:
    kind: Deployment
    fieldPath: spec.template.spec.containers[3].args[2]
    value: 0000000000000000000000000000000000000000000000000000000000000001

- source:
    kind: Deployment
    fieldPath: spec.template.spec.containers[3].args[4]
    value: /dns/alice-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
