apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/base.yaml

resources:
- base.yaml

source: kind: Deployment fieldPath: metadata.namePrefix value: alice
source: kind: Deployment fieldPath: spec.template.spec.containers[3].args[2] value: 0000000000000000000000000000000000000000000000000000000000000001
source: kind: Deployment fieldPath: spec.template.spec.containers[3].args[4] value: /dns/alice-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp