apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/base.yaml
  - configmap.yaml

namePrefix: alice

replacements:
- source:
    kind: ConfigMap
    name: alice-configmap
  targets:
  - select:
      fieldPaths:
      - spec.template.spec.containers.[name=substrate-node].env.[name=node-key].value
    values:
      - value: "0000000000000000000000000000000000000000000000000000000000000001"
  - select:
      fieldPaths:
      - spec.template.spec.containers.[name=substrate-node].args.[name=bootnodes].value
    values:
      - value: "/dns/alice-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
