apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/base.yaml
  - configmap.yaml

namePrefix: alice

replacements:
- source:
    kind: ConfigMap
    name: alice-configmap
  targets:
  - select:
      fieldPaths:
      - spec.template.spec.containers.[name=substrate-node].args.[name=node-key].value
      - spec.template.spec.containers.[name=substrate-node].args[name=bootnodes].value.
    values:
      - "2222222222222222222222222222222222222222222222222222222222222222"
      - "/dns/charlie-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/56D7KooM8iJAsdfghj8765fghjkoU78dfGh9kjHji4fdA8gJ4wF"