apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replacements:
- source:
    kind: string
    name: alice
  targets:
  - select:
      name: hello
      kind: Job
    fieldPaths: 
    - spec.template.spec.containers[3].args[0]