---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dave-claim-postgres-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dave-postgres-data
  namespace: sc
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  awsElasticBlockStore:
    volumeID: vol-084129b14eaa60d8a 
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dave-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dave-claim-substrate-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass 
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dave-claim-vector-logs
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi