apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/base.yaml
  -  configmap.yaml

namePrefix: bob

replacements:
- source:
    kind: ConfigMap
    name: bob-configmap
  targets:
  - select:
      fieldPaths:
      - spec.template.spec.containers.[name=substrate-node].args.[name=node-key].value
    values:
      - "0000000000000000000000000000000000000000000000000000000000000002"
  - select:
      fieldPaths:
      - spec.template.spec.containers.[name=substrate-node].args.[name=bootnodes].value
    values:
      - "/dns/alice-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXw