---
apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/github-runner:v2.307.0
        imagePullPolicy: IfNotPresent
        #resources:
        #  limits:
        #    memory: "300Mi"
        #    cpu: "1000m"
        #  requests:
        #    memory: "300Mi"
        #    cpu: "1000m"
