---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sidechains-test-github-runner
spec:
  replicas: 1
  template:
    spec:
      repository: input-output-hk/sidechains-test
