---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eve-claim-postgres-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: sc
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  awsElasticBlockStore:
    volumeID: vol-06a69f9f6300e6e21 
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eve-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eve-claim-substrate-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eve-claim-vector-logs
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi