---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-6-claim-postgres-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stack-6-postgres-data
  namespace: sc
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  awsElasticBlockStore:
    volumeID: vol-0f9b984aae6ecf403
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-6-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-6-claim-substrate-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-6-claim-db-sync-state-dir
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-6-claim-vector-logs
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi
