apiVersion: v1
data:
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::689191102645:role/default-eks-node-group-20230510163522054800000003"
      "username": "system:node:{{EC2PrivateDNSName}}"
  mapUsers: |
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::689191102645:user/*"
      "username": "*"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-10T16:48:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4529333"
  uid: 7b01bfed-a8ee-420a-b3ef-22ce19559ddf
