{{- range .Values.pods }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}-cardano-node
  labels:
    app: {{ .name }}-cardano-node
spec:
  containers:
    - name: cardano-node
      image: {{ $.Values.images.cardanoNode }}
      env:
        {{- range $key, $value := $.Values.envs['cardano-node'] }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
      ports:
        {{- range $.Values.ports.cardanoNode }}
        - name: tcp-{{ . }}
          containerPort: {{ . }}
        {{- end }}
      volumeMounts:
        - name: ipc
          mountPath: /ipc
        - name: datavol
          mountPath: /opt/cardano/data
  volumes:
    - name: ipc
      emptyDir: {}
    - name: datavol
      emptyDir: {}
{{- end }}
