{{- range .Values.pods }}
{{- range $key, $value := $.Values.images }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-{{ $key }}-service
spec:
  selector:
    app: {{ .name }}
  ports:
  {{- range $port := index $.Values.ports $key }}
  - protocol: TCP
    port: {{ $port }}
    targetPort: {{ $port }}
  {{- end }}
---
{{- end }}
{{- end }}
