{{- range .Values.pods }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}-vector
  labels:
    app: {{ .name }}-vector
spec:
  containers:
    - name: vector
      image: {{ $.Values.images.vector }}
      ports:
        {{- range $.Values.ports.vector }}
        - name: tcp-{{ . }}
          containerPort: {{ . }}
        {{- end }}
      volumeMounts:
        - name: vector-config-volume
          mountPath: /etc/vector
        - name: logs
          mountPath: /var/log
  volumes:
    - name: vector-config-volume
      configMap:
        name: vector-config
    - name: logs
      emptyDir: {}
{{- end }}
