---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sidechains-test-github-runner
spec:
  replicas: 1
  template:
    spec:
      repository: input-output-hk/sidechains-tests
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "2Gi"