resources:
  - ../base/base.yaml

namePrefix: charlie
vars:
- name: node-key
  values:
    - "0000000000000000000000000000000000000000000000000000000000000003"
- name: bootnodes
  values:
    - "/dns/alice-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"