#  This configuration creates a service named substrate-service which other services can use to discover the Pods in the StatefulSet.
#  - Uses Dockerhub image parity/substrate 
#  - Ports 30333, 9933, 9944, and 9615 are exposed.
#  - A PersistentVolumeClaim named chain-data is attached to the Pod, which ensures the data in /chain-data persists across Pod restarts. The access mode is ReadWriteOnce, which means the volume can be mounted as read-write by a single node.

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: substrate-node
spec:
  serviceName: "substrate-service"
  replicas: 1
  selector:
    matchLabels:
      app: substrate-node
  template:
    metadata:
      labels:
        app: substrate-node
    spec:
      containers:
      - name: substrate-node
        image: parity/substrate
        ports:
        - containerPort: 30333
          name: p2p
        - containerPort: 9933
          name: rpc
        - containerPort: 9944
          name: ws
        - containerPort: 9615
          name: metrics
        volumeMounts:
        - name: chain-data
          mountPath: /chain-data
  volumeClaimTemplates:
  - metadata:
      name: chain-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
