apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: ArgoCD project for sidechains-infra
  sourceRepos:
    - 'https://github.com/input-output-hk/sidechains-infra'
  destinations:
    - namespace: monitoring
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
