apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml

vars:
- name: POD_NAME
  objref:
    kind: ConfigMap
    name: alice-configmap
    apiVersion: v1
  fieldref:
    fieldpath: data.podName