apiVersion: v1
kind: Namespace
metadata:
  name: sidechains-substrate-poc-3
# $(namePrefix)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: $(namePrefix)-vector-config
  namespace: sidechains-substrate-poc-3
data:
  vector.toml: |
    [api]
    enabled = true
    address = "0.0.0.0:8686"
    [sources.log_file]
    type = "file"
    include = ["/var/log/*.log"]
    # [sinks.prometheus]
    # type = "prometheus_exporter"
    # inputs = [ "my-source-or-transform-id" ]
    [sinks.console]
    inputs = ["log_file"]
    target = "stdout"
    type = "console"
    encoding.codec = "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: $(namePrefix)-secrets
  namespace: sidechains-substrate-poc-3
data:
  postgres_db: "cexplorer"
  postgres_user: "postgres"
  postgres_password: "password123"
---
apiVersion: v1
kind: Pod
metadata:
  name: $(namePrefix)
  namespace: sidechains-substrate-poc-3
  labels:
    app: $(namePrefix)
    node: $(namePrefix)
spec:
  containers:
    - name: $(namePrefix)-cardano-node
      image: inputoutput/cardano-node:8.0.0 
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "1024Mi"
          cpu: "1000m"
        requests:
          memory: "1024Mi"
          cpu: "1000m"
      env:
        - name: NETWORK
          value: "preview"
        - name: CARDANO_NODE_SOCKET_PATH
          value: /ipc/node.socket
      volumeMounts:
        - name: $(namePrefix)-ipc
          mountPath: /ipc
        - name: $(namePrefix)-data
          mountPath: /opt/cardano/data
    - name: $(namePrefix)-db-sync
      image: inputoutput/cardano-db-sync:latest 
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "2000m"
        requests:
          memory: "4096Mi"
          cpu: "2000m"
      env:
        - name: NETWORK
          value: "preview"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - name: $(namePrefix)-ipc
          mountPath: /node-ipc
        - name: $(namePrefix)-postgres-run
          mountPath: /run/postgresql
        - name: $(namePrefix)-secrets
          mountPath: /run/secrets
    - name: $(namePrefix)-postgres
      image: postgres:15.3
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "2000m"
        requests:
          memory: "4096Mi"
          cpu: "2000m"
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
        - name: POSTGRES_DB
          value: "cexplorer"
      volumeMounts:
        - name: $(namePrefix)-data
          mountPath: /var/lib/postgresql/data
        - name: $(namePrefix)-postgres-run
          mountPath: /run/postgresql
    - name: $(namePrefix)-bridge-backend
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/bridge-backend
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "1000m"
        requests:
          memory: "512Mi"
          cpu: "1000m"
      volumeMounts:
      - name: $(namePrefix)-ipc
        mountPath: /node-ipc
      - name: $(namePrefix)-data
        mountPath: /var/lib/postgresql/data
    - name: $(namePrefix)-substrate-node
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/sidechains-substrate-node
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "300m"
        requests:
          memory: "512Mi"
          cpu: "300m"
      args: 
         - "--name"
         - "$(namePrefix)"
         - "--base-path"
         - "/data/$(namePrefix)"
         - "--chain"
         - "local"
         - "--validator"
         - "--node-key"
         - $(my-configmap.data.$(namePrefix)-node-key)
      ports:
         - containerPort: 30333
           name: p2p
         - containerPort: 9945
           name: ws-port
         - containerPort: 9933
           name: rcp-port
      volumeMounts:
         - name: $(namePrefix)-data
           mountPath: /data
    - name: $(namePrefix)-vector
      image: timberio/vector:nightly-alpine
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "300Mi"
          cpu: "300m"
        requests:
          memory: "300Mi"
          cpu: "300m"
      ports:
        - containerPort: 8686 
      volumeMounts:
        - name: $(namePrefix)-vector-config
          mountPath: /etc/vector
        - name: $(namePrefix)-vector-logs
          mountPath: /var/log
  volumes:
    - name: $(namePrefix)-data
      emptyDir: {}
    - name: $(namePrefix)-ipc
      emptyDir: {}
    - name: $(namePrefix)-postgres-run
      emptyDir: {}
    - name: $(namePrefix)-secrets
      configMap:
        name: $(namePrefix)-secrets
    - name: $(namePrefix)-vector-config
      configMap:
        name: $(namePrefix)-vector-config
    - name: $(namePrefix)-vector-logs
      emptyDir: {}