---
apiVersion: v1
kind: Service
metadata:
  name: gh-actions-postgres-service
  namespace: sc
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
---
apiVersion: v1
kind: Pod
metadata:
  name: gh-actions-postgres
  namespace: sc
  labels:
    app: sidechains-substrate-poc
    node: gh-actions-postgres
spec:
  containers:
    - name: postgres
      image: postgres:15.3
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "1024Mi"
          cpu: "500m"
        requests:
          memory: "1024Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "gh-actions-postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: gh-actions-postgres-claim-postgres-data
    