---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gh-actions-postgres-claim-postgres-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 90Gi