---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gh-actions-postgres-claim-postgres-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 90Gi


#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: gh-actions-postgres-claim-postgres-data
#  namespace: sc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: aws-ebs-storageclass
#  resources:
#    requests:
#      storage: 90Gi
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: gh-actions-postgres-data
#  namespace: sc
#spec:
#  capacity:
#    storage: 90Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: aws-ebs-storageclass
#  awsElasticBlockStore:
#    volumeID: vol-0d205571e5e547202 
#    fsType: ext4