---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unzen-claim-cardano-node-1-data
  namespace: unzen
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi

