---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-vector
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-loki
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: aws-ebs-storageclass
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 100Gi
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: monitoring-loki
#  namespace: monitoring
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: aws-ebs-storageclass
#  awsElasticBlockStore:
#    volumeID: vol-09187d3de62643b44
#    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-prometheus
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi