---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-vector
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-loki
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-prometheus
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-claim-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi