---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'pagerduty'
      routes:
      - match:
          severity: critical
        receiver: pagerduty
          
    receivers:
    - name: 'pagerduty'
      pagerduty_configs:
      - service_key: '<PAGERDUTY_INTEGRATION_KEY>'
        send_resolved: true
