---
apiVersion: v1
kind: Service
metadata:
  name: eve-service
  namespace: sidechains-substrate-poc-4
spec:
  type: NodePort
  selector:
    app: sidechains-substrate-poc
    node: eve
  ports:
    - name: tcp-30333
      port: 30333
      targetPort: 30333
    - name: tcp-9946
      port: 9946
      targetPort: 9946
    - name: tcp-9934
      port: 9934
      targetPort: 9934
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eve-vector-config
  namespace: sidechains-substrate-poc-4
data:
  vector.toml: |
    [api]
    enabled = true
    address = "0.0.0.0:8686"
    [sources.log_file]
    type = "file"
    include = ["/var/log/*.log"]
    # [sinks.prometheus]
    # type = "prometheus_exporter"
    # inputs = [ "my-source-or-transform-id" ]
    [sinks.console]
    inputs = ["log_file"]
    target = "stdout"
    type = "console"
    encoding.codec = "json"
---
apiVersion: v1
kind: Pod
metadata:
  name: eve
  namespace: sidechains-substrate-poc-4
  labels:
    app: sidechains-substrate-poc
    node: eve
spec:
  containers:
    - name: cardano-node
      image: inputoutput/cardano-node:8.0.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "2048Mi"
          cpu: "1000m"
        requests:
          memory: "2048Mi"
          cpu: "1000m"
      env:
        - name: NETWORK
          value: "preview"
        - name: CARDANO_NODE_SOCKET_PATH
          value: /ipc/node.socket
      volumeMounts:
        - name: eve-ipc
          mountPath: /ipc
        - name: eve-data
          mountPath: /opt/cardano/data
    - name: db-sync
      image: inputoutput/cardano-db-sync:13.1.1.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "2000m"
        requests:
          memory: "4096Mi"
          cpu: "2000m"
      env:
        - name: NETWORK
          value: "preview"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - name: eve-ipc
          mountPath: /node-ipc
        - name: eve-cexplorer
          mountPath: /run/postgresql
    - name: postgres
      image: postgres:15.3
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "2048Mi"
          cpu: "1000m"
        requests:
          memory: "2048Mi"
          cpu: "1000m"
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB
          value: "cexplorer"
      volumeMounts:
        - name: eve-postgres-data
          mountPath: /var/lib/postgresql/data
    - name: bridge-backend
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/bridge-backend:0.0.17
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "512Mi"
          cpu: "500m"
      env:
        - name: CARDANO_FOLLOWER_POSTGRES_USERNAME
          value: "postgres"
        - name: CARDANO_FOLLOWER_POSTGRES_PASSWORD
          value: "password123"
        - name: CARDANO_FOLLOWER_JDBC_URL
          value: "jdbc:postgresql://localhost:5432/cexplorer"
      volumeMounts:
        - name: eve-ipc
          mountPath: /local
    - name: substrate-node
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/sidechains-substrate-node:v0.0.3
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "1024Mi"
          cpu: "1000m"
        requests:
          memory: "1024Mi"
          cpu: "1000m"
      args:
        - "--eve"
        - "--base-path"
        - "/data"
        - "--chain"
        - "local"
        - "--validator"
        - "--node-key"
        - "0000000000000000000000000000000000000000000000000000000000000002"
        - "--bootnodes"
        - "/dns/alice-service.sidechains-substrate-poc-4.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      ports:
        - containerPort: 30333
          name: p2p
        - containerPort: 9945
          name: ws-port
        - containerPort: 9933
          name: rcp-port
      volumeMounts:
        - name: eve-data
          mountPath: /data
    - name: vector
      image: timberio/vector:nightly-alpine
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "300Mi"
          cpu: "300m"
        requests:
          memory: "300Mi"
          cpu: "200m"
      ports:
        - containerPort: 8686
      volumeMounts:
        - name: eve-vector-config
          mountPath: /etc/vector
        - name: eve-vector-logs
          mountPath: /var/log
  volumes:
    - name: eve-data
      emptyDir: {}
    - name: eve-ipc
      emptyDir: {}
    - name: eve-postgres-data
      emptyDir: {}
    - name: eve-cexplorer
      emptyDir: {}
    - name: eve-vector-config
      configMap:
        name: eve-vector-config
    - name: eve-vector-logs
      emptyDir: {}
