apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/base.yaml
  - configmap.yaml

namePrefix: eve

replacements:
  - source:
      kind: ConfigMap
      name: eve-configmap
    targets:
      - select:
          fieldPaths:
            - spec.template.spec.containers.[name=substrate-node].env.[name=node-key].value
        values:
          - value: "0000000000000000000000000000000000000000000000000000000000000005"
      - select:
          fieldPaths:
            - spec.template.spec.containers.[name=substrate-node].args.[name=bootnodes].value
        values:
          - value: "/dns/charlie-service.sidechains-substrate-poc.svc.cluster.local/tcp/30333/p2p/56D7KooM8iJAsdfghj8765fghjkoU78dfGh9kjHji4fdA8gJ4wF"
