---
apiVersion: v1
kind: Service
metadata:
  name: bob-service
  namespace: sc
spec:
  type: NodePort
  selector:
    app: sidechains-substrate-poc
    node: bob
  ports:
    - name: p2p-port
      port: 30333
      targetPort: 30333
      nodePort: 30002
    - name: ws-port
      port: 9945
      targetPort: 9945
      nodePort: 30012
    - name: rpc-port
      port: 9933
      targetPort: 9933
      nodePort: 30022
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bob-vector-configmap
  namespace: sc
data:
  vector.toml: |
    [api]
    enabled = true
    address = "0.0.0.0:8686"
    [sources.log_file]
    type = "file"
    include = ["/var/log/*.log"]
    # [sinks.prometheus]
    # type = "prometheus_exporter"
    # inputs = [ "my-source-or-transform-id" ]
    [sinks.console]
    inputs = ["log_file"]
    target = "stdout"
    type = "console"
    encoding.codec = "json"
---
apiVersion: v1
kind: Pod
metadata:
  name: bob
  namespace: sc
  labels:
    app: sidechains-substrate-poc
    node: bob
    substrate-node: 'true'
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: substrate-node
            operator: In
            values:
            - 'true'
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    pod: bob
  containers:
    - name: cardano-node
      image: inputoutput/cardano-node:8.0.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "2048Mi"
          cpu: "1500m"
        requests:
          memory: "2048Mi"
          cpu: "1500m"
      env:
        - name: NETWORK
          value: "preview"
        - name: CARDANO_NODE_SOCKET_PATH
          value: /ipc/node.socket
      volumeMounts:
        - name: ipc
          mountPath: /ipc
        - name: cardano-node-data
          mountPath: /data
    - name: db-sync
      image: inputoutput/cardano-db-sync:13.1.1.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "4096Mi"
          cpu: "1000m"
        requests:
          memory: "4096Mi"
          cpu: "1000m"
      env:
        - name: NETWORK
          value: "preview"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_PORT
          value: "5432"
      volumeMounts:
        - name: ipc
          mountPath: /node-ipc
    - name: postgres
      image: postgres:15.3
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "2048Mi"
          cpu: "1000m"
        requests:
          memory: "2048Mi"
          cpu: "1000m"
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password123"
        - name: POSTGRES_DB
          value: "cexplorer"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
    - name: bridge-backend
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/bridge-backend-mock:0.0.1
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "512Mi"
          cpu: "1000m"
        requests:
          memory: "512Mi"
          cpu: "1000m"
      env:
        - name: CARDANO_FOLLOWER_POSTGRES_USERNAME
          value: "postgres"
        - name: CARDANO_FOLLOWER_POSTGRES_PASSWORD
          value: "password123"
        - name: CARDANO_FOLLOWER_JDBC_URL
          value: "jdbc:postgresql://localhost:5432/cexplorer"
      volumeMounts:
        - name: ipc
          mountPath: /ipc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
    - name: substrate-node
      image: 689191102645.dkr.ecr.eu-central-1.amazonaws.com/substrate-node:v0.0.6-pre2
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "1024Mi"
          cpu: "1500m"
        requests:
          memory: "1024Mi"
          cpu: "1500m"
      env:
        - name: MC_FIRST_EPOCH_TIMESTAMP_MILLIS
          value: "1666656000000"
        - name: MC_FIRST_EPOCH_NUMBER
          value: "0"
        - name: MC_EPOCH_DURATION_MILLIS
          value: "86400000"
      args:
        - "--bob"
        - "--base-path"
        - "/data"
        - "--chain"
        - "local"
        - "--validator"
        - "--node-key"
        - "0000000000000000000000000000000000000000000000000000000000000002"
        - "--bootnodes"
        - "/dns/alice-service.sc.svc.cluster.local/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
        - "--unsafe-rpc-external"
        - "--rpc-port"
        - "9933"
        - "--unsafe-ws-external"
        - "--ws-port"
        - "9945"
      ports:
        - containerPort: 30333
          name: p2p
        - containerPort: 9945
          name: ws-port
        - containerPort: 9933
          name: rpc-port
      volumeMounts:
        - name: substrate-node-data
          mountPath: /data
        - name: ipc
          mountPath: /ipc
    - name: vector
      image: timberio/vector:nightly-alpine
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "300Mi"
          cpu: "1000m"
        requests:
          memory: "300Mi"
          cpu: "1000m"
      ports:
        - containerPort: 8686
      volumeMounts:
        - name: vector-config
          mountPath: /etc/vector
        - name: vector-logs
          mountPath: /var/log

  volumes:
    - name: cardano-node-data
      persistentVolumeClaim:
        claimName: bob-claim-cardano-node-data
    - name: postgres-data
      persistentVolumeClaim:
        claimName: bob-claim-postgres-data
    - name: substrate-node-data
      persistentVolumeClaim:
        claimName: bob-claim-substrate-node-data
    - name: ipc
      emptyDir: {}
    - name: vector-config
      configMap:
        name: bob-vector-configmap
    - name: vector-logs
      persistentVolumeClaim:
        claimName: bob-claim-vector-logs
