---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bob-claim-postgres-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bob-postgres-data
  namespace: sc
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-storageclass
  awsElasticBlockStore:
    volumeID: vol-0c20e02fb3ccd2e41
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bob-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass 
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bob-claim-substrate-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bob-claim-vector-logs
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi