---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: charlie-claim-cardano-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: charlie-claim-postgres-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: charlie-postgres-data-ebs-sc-2
  resources:
    requests:
      storage: 90Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: charlie-claim-substrate-node-data
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: charlie-claim-vector-logs
  namespace: sc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs-storageclass
  resources:
    requests:
      storage: 10Gi